# Generated by Django 4.2.15 on 2024-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0005_alter_product_immagine_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
    ]
