# Generated by Django 4.2.15 on 2024-09-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0006_rename_name_category_nome_alter_product_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='homestore.category'),
        ),
    ]
