# Generated by Django 4.2.15 on 2024-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0010_alter_product_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='immagine',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
