# Generated by Django 4.2.15 on 2024-09-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homestore', '0014_userpurchase_productpurchaseassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homestore.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestore.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userpurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductPurchaseAssociation',
        ),
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
