# Generated by Django 4.2.15 on 2024-11-28 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0019_remove_cart_created_at_remove_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
