# Generated by Django 4.2.15 on 2024-11-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0020_cart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homestore.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestore.product')),
            ],
        ),
    ]
