# Generated by Django 4.2.15 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0025_remove_cartitem_user_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='homestore.cartitem'),
        ),
    ]
