# Generated by Django 4.2.15 on 2024-12-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0026_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colore',
            field=models.CharField(blank=True, choices=[('red', 'Rosso'), ('blue', 'Blu'), ('green', 'Verde'), ('black', 'Nero'), ('white', 'Bianco')], max_length=50, null=True),
        ),
    ]
