# Generated by Django 4.2.15 on 2024-12-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0029_alter_product_colore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='Codice colore HEX, ad esempio: #FF5733', max_length=7, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colore',
        ),
        migrations.AddField(
            model_name='product',
            name='colori',
            field=models.ManyToManyField(related_name='products', to='homestore.color'),
        ),
    ]
