# Generated by Django 4.2.15 on 2024-12-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0031_orderitem_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colors',
        ),
    ]
