# Generated by Django 4.2.15 on 2024-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0032_remove_orderitem_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colori',
            field=models.ManyToManyField(blank=True, to='homestore.color'),
        ),
    ]
