# Generated by Django 4.2.15 on 2024-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0033_alter_product_colori'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='red', max_length=7),
        ),
    ]
