# Generated by Django 4.2.15 on 2024-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0034_cartitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
