# Generated by Django 4.2.15 on 2024-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0035_alter_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
