# Generated by Django 4.2.15 on 2024-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0037_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
