# Generated by Django 4.2.15 on 2024-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0038_order_ready_for_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa di ritiro'), ('completed', 'Ritirato'), ('cancelled', 'Annullato'), ('preparing', 'In preparazione')], default='pending', max_length=10),
        ),
    ]
