# Generated by Django 4.2.15 on 2024-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('completed', 'Ritirato'), ('cancelled', 'Annullato')], default='pending', max_length=10),
        ),
    ]
