# Generated by Django 4.2.15 on 2024-12-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestore', '0041_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
